name = "tiny-frontent-api-cloudlare-example"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-30"

kv_namespaces = [
    { binding = "TinyFrontendKv", id = "7113fb20c2464dcc9c521f8b0bb4d45e", preview_id = "81443b04b2c543f6bcd8305d23d3bf6c" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
